language: cpp

services:
  - docker

before_install:
  - docker pull rootproject/root-ubuntu16:latest
  - docker run -itd -v $TRAVIS_BUILD_DIR:$TRAVIS_BUILD_DIR --name root-docker rootproject/root-ubuntu16:latest

script:
  - docker exec root-docker $TRAVIS_BUILD_DIR/.travis/ciscript.sh